services:
  rabbitmq:
    image: rabbitmq:management

  databasea:
    image: mcr.microsoft.com/mssql/server

  databaseb:
    image: mcr.microsoft.com/mssql/server

  systema.api:
    image: ${DOCKER_REGISTRY-}systemaapi
    build:
      context: .
      dockerfile: src/SystemA.API/Dockerfile

  systemb.api:
    image: ${DOCKER_REGISTRY-}systembapi
    build:
      context: .
      dockerfile: src/SystemB.API/Dockerfile

