services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
 
  databasea:
    container_name: databasea
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HardPassword12345678abc!
    restart: always
    ports:
      - "1493:1433"
 
  databaseb:
    container_name: databaseb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HardPassword12345678abc!
    restart: always
    ports:
      - "1494:1433"

  systema.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=databasea;Database=SystemA_DB;User Id=sa;Password=HardPassword12345678abc!;Encrypt=False;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    depends_on:
      - databasea
      - rabbitmq
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  systemb.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=databaseb;Database=SystemB_DB;User Id=sa;Password=HardPassword12345678abc!;Encrypt=False;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    depends_on:
      - databaseb
      - rabbitmq
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
